name: Markdown Lint

on:
  push:
    paths:
      - "**.md"
    branches: [main]
  pull_request:
    paths:
      - "**.md"
    branches: [main]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run Markdown Lint
        run: markdownlint '**/*.md' --ignore node_modules

      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "no"
          config-file: ".github/workflows/mlc_config.json"
          folder-path: "."
